### ISSUE TITLE
Minimised objectives lead to mirrored palinstance.means

### ISSUE THREAD

**Issue by FMcil** [kjappelbaum/pyepal#185]
Hi! I noticed some unexpected behaviour when minimising objectives. This isn't really a bug and the workaround is quite simple.

## Steps to reproduce the problem

- Set `goals` to any combination involving min
- Perform active learning using exhaust loop
- Observe that `palinstance.means` gives expected values for maximised objectives
- Observe that `palinstance.means` gives mirrored values for minimised objectives (multiplying it by -1 gives correct predictions)
- Observe that using `.predict` with the models gives mirrored values for minimised objectives (multiplying it by -1 gives correct predictions)

[Here](https://deepnote.com/project/Pyepal-mirrored-results-Yeuc095QRE6ToMXFtwFjnA/%2Fbinh_korn_goals_issue.ipynb) is a notebook detailing the issue.

## Specifications

- pyepal version: 0.6.1
- operating system: DeepNote cloud
- Python version: 3.7

**Comment by kjappelbaum** [comment]
you're a fan of DeepNote? :D

**Comment by FMcil** [comment]
> you're a fan of DeepNote? :D

I'm a fan of anyone who gives me free swag and computing hours 👍

**Comment by kjappelbaum** [comment]
has this issue been fixed with #186 ?

**Comment by kjappelbaum** [comment]
assuming that this is fixed now
